// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx0tMJ3s9KjZzEOcMy1I1IZwe66ISAAq8',
    appId: '1:134534962028:web:05314c683ce31375df3149',
    messagingSenderId: '134534962028',
    projectId: 'flutter-auth-codelab-6bd2d',
    authDomain: 'flutter-auth-codelab-6bd2d.firebaseapp.com',
    storageBucket: 'flutter-auth-codelab-6bd2d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC69Z-2Bd5t6ZPvj11NcmRvJ_NLkBSOIrU',
    appId: '1:134534962028:android:e867f4b138806880df3149',
    messagingSenderId: '134534962028',
    projectId: 'flutter-auth-codelab-6bd2d',
    storageBucket: 'flutter-auth-codelab-6bd2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANw-S1a-AYoFptbW68yrkY_ytiQF9Jfsc',
    appId: '1:134534962028:ios:93fd1c02b6e36695df3149',
    messagingSenderId: '134534962028',
    projectId: 'flutter-auth-codelab-6bd2d',
    storageBucket: 'flutter-auth-codelab-6bd2d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthFlutterfireUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANw-S1a-AYoFptbW68yrkY_ytiQF9Jfsc',
    appId: '1:134534962028:ios:93fd1c02b6e36695df3149',
    messagingSenderId: '134534962028',
    projectId: 'flutter-auth-codelab-6bd2d',
    storageBucket: 'flutter-auth-codelab-6bd2d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthFlutterfireUi',
  );
}
